package com.techm.pmo.dto;
// Generated Jul 29, 2019 8:35:46 PM by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;

import com.techm.pmo.model.User;

/**
 * TOsHrUser generated by hbm2java
 */
/*@Entity
@Table(name = "t_pmr", catalog = "pmox")*/
public class PmrData implements java.io.Serializable {

  private String projectId;
  private String projectDesc;
  private String buisnessUnit;
  private int    custId;
  private String ibuName;
  private String ibuHeadName;
  private String ibuDesc;
  private String status;
  private String ibgName;
  private String projMainTyp;
  private String projectType;
  private String   projStartDt;
  private String   projEndDt;
  private String programMangrNm;
  private String pmDelegateNm;
  private String projMangerNm;
  private int    activeHeadCount;
  private int    onsActHeadCnt;
  private int    offActHeadCnt;
  private List<String> project =new ArrayList<String>();
  private List<User> projectManager;

  public PmrData() {}

  /*public PmrData(String projectId, String projectDesc, Integer custId, String ibuName,
      String ibuHeadName, String status, String ibgName, String projMainTyp, Date projStartDt,
      Date projEndDt, String programMangrNm, String pmDelegateNm, String projMangerNm,
      Integer activeHeadCount, Integer onsActHeadCnt, Integer offActHeadCnt,List<String> project,String buisnessUnit,String  ibuDesc) {

    this.projectId = projectId;
    this.projectDesc = projectDesc;
    this.custId = custId;
    this.ibuName = ibuName;
    this.ibuHeadName = ibuHeadName;
    this.status = status;
    this.ibgName = ibgName;
    this.projMainTyp = projMainTyp;
    this.projStartDt = projStartDt;
    this.projEndDt = projEndDt;
    this.programMangrNm = programMangrNm;
    this.pmDelegateNm = pmDelegateNm;
    this.projMangerNm = projMangerNm;
    this.activeHeadCount = activeHeadCount;
    this.onsActHeadCnt = onsActHeadCnt;
    this.offActHeadCnt = offActHeadCnt;
    this.project=project;
    this.buisnessUnit=buisnessUnit;
    this.ibuDesc=ibuDesc;

  }*/

  public String getProjectId() {
    return projectId;
  }
  
 
  public void setProjectId(String projectId) {
    this.projectId = projectId;
  }

  public String getProjectDesc() {
    return projectDesc;
  }

  public void setProjectDesc(String projectDesc) {
    this.projectDesc = projectDesc;
  }

  public int getCustId() {
    return custId;
  }

  public void setCustId(int custId) {
    this.custId = custId;
  }

 
  public String getIbuName() {
    return ibuName;
  }

  public void setIbuName(String ibuName) {
    this.ibuName = ibuName;
  }

  public String getIbuHeadName() {
    return ibuHeadName;
  }

  public void setIbuHeadName(String ibuHeadName) {
    this.ibuHeadName = ibuHeadName;
  }

  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public String getIbgName() {
    return ibgName;
  }

  public void setIbgName(String ibgName) {
    this.ibgName = ibgName;
  }

  public String getProjMainTyp() {
    return projMainTyp;
  }

  public void setProjMainTyp(String projMainTyp) {
    this.projMainTyp = projMainTyp;
  }

  public String getProjectType() {
    return projectType;
  }

  public void setProjectType(String projectType) {
    this.projectType = projectType;
  }

  public String getProjStartDt() {
    return projStartDt;
  }

  public void setProjStartDt(String projStartDt) {
    this.projStartDt = projStartDt;
  }

  public String getProjEndDt() {
    return projEndDt;
  }

  public void setProjEndDt(String projEndDt) {
    this.projEndDt = projEndDt;
  }

  public String getProgramMangrNm() {
    return programMangrNm;
  }

  public void setProgramMangrNm(String programMangrNm) {
    this.programMangrNm = programMangrNm;
  }

  public String getPmDelegateNm() {
    return pmDelegateNm;
  }

  public void setPmDelegateNm(String pmDelegateNm) {
    this.pmDelegateNm = pmDelegateNm;
  }

  public String getProjMangerNm() {
    return projMangerNm;
  }

  public void setProjMangerNm(String projMangerNm) {
    this.projMangerNm = projMangerNm;
  }

  public int getActiveHeadCount() {
    return activeHeadCount;
  }

  public void setActiveHeadCount(int activeHeadCount) {
    this.activeHeadCount = activeHeadCount;
  }

  public int getOnsActHeadCnt() {
    return onsActHeadCnt;
  }

  public void setOnsActHeadCnt(int onsActHeadCnt) {
    this.onsActHeadCnt = onsActHeadCnt;
  }

  public int getOffActHeadCnt() {
    return offActHeadCnt;
  }

  public void setOffActHeadCnt(int offActHeadCnt) {
    this.offActHeadCnt = offActHeadCnt;
  }

public List<String> getProject() {
	return project;
}

public void setProject(List<String> project) {
	this.project = project;
}

public String getBuisnessUnit() {
	return buisnessUnit;
}

public void setBuisnessUnit(String buisnessUnit) {
	this.buisnessUnit = buisnessUnit;
}

public String getIbuDesc() {
	return ibuDesc;
}

public void setIbuDesc(String ibuDesc) {
	this.ibuDesc = ibuDesc;
}
 

public List<User> getProjectManager() {
  return projectManager;
}

public void setProjectManager(List<User> projectManager) {
  this.projectManager = projectManager;
}

  

}
