package com.techm.pmo.model;
// Generated Jul 29, 2019 8:35:46 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.BatchSize;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TOsHrUser generated by hbm2java
 */
/*@Entity
@Table(name = "t_pmr", catalog = "pmox")*/
public class Pmrdata implements java.io.Serializable {

  private String projectId;
  private String projectDesc;
  private int    custId;
  private String ibuName;
  private String ibuHeadName;
  private String status;
  private String ibgName;
  private String projMainTyp;
  private String projectType;
  private Date   projStartDt;
  private Date   projEndDt;
  private String programMangrNm;
  private String pmDelegateNm;
  private String projMangerNm;
  private int    activeHeadCount;
  private int    onsActHeadCnt;
  private int    offActHeadCnt;

  public Pmrdata() {}

  public Pmrdata(String projectId, String projectDesc, Integer custId, String ibuName,
      String ibuHeadName, String status, String ibgName, String projMainTyp, Date projStartDt,
      Date projEndDt, String programMangrNm, String pmDelegateNm, String projMangerNm,
      Integer activeHeadCount, Integer onsActHeadCnt, Integer offActHeadCnt) {

    this.projectId = projectId;
    this.projectDesc = projectDesc;
    this.custId = custId;
    this.ibuName = ibuName;
    this.ibuHeadName = ibuHeadName;
    this.status = status;
    this.ibgName = ibgName;
    this.projMainTyp = projMainTyp;
    this.projStartDt = projStartDt;
    this.projEndDt = projEndDt;
    this.programMangrNm = programMangrNm;
    this.pmDelegateNm = pmDelegateNm;
    this.projMangerNm = projMangerNm;
    this.activeHeadCount = activeHeadCount;
    this.onsActHeadCnt = onsActHeadCnt;
    this.offActHeadCnt = offActHeadCnt;

  }

  //@Column(name = "projectId")
  public String getProjectId() {
    return projectId;
  }
  
 
  public void setProjectId(String projectId) {
    this.projectId = projectId;
  }

  //@Column(name = "projectDesc")
  public String getProjectDesc() {
    return projectDesc;
  }

  public void setProjectDesc(String projectDesc) {
    this.projectDesc = projectDesc;
  }

  //@Column(name = "custId")
  public int getCustId() {
    return custId;
  }

  public void setCustId(int custId) {
    this.custId = custId;
  }

  //@Column(name = "IBU")
  public String getIbuName() {
    return ibuName;
  }

  public void setIbuName(String ibuName) {
    this.ibuName = ibuName;
  }

  //@Column(name = "IbuHeadName")
  public String getIbuHeadName() {
    return ibuHeadName;
  }

  public void setIbuHeadName(String ibuHeadName) {
    this.ibuHeadName = ibuHeadName;
  }

  //@Column(name = "Status")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  //@Column(name = "IBG")
  public String getIbgName() {
    return ibgName;
  }

  public void setIbgName(String ibgName) {
    this.ibgName = ibgName;
  }

  //@Column(name = "Project_Main_Type")
  public String getProjMainTyp() {
    return projMainTyp;
  }

  public void setProjMainTyp(String projMainTyp) {
    this.projMainTyp = projMainTyp;
  }

  //@Column(name = "Project_Type")
  public String getProjectType() {
    return projectType;
  }

  public void setProjectType(String projectType) {
    this.projectType = projectType;
  }

  //@Column(name = "Project_Start_Date")
  public Date getProjStartDt() {
    return projStartDt;
  }

  public void setProjStartDt(Date projStartDt) {
    this.projStartDt = projStartDt;
  }

  //@Column(name = "Project_End_Date")
  public Date getProjEndDt() {
    return projEndDt;
  }

  public void setProjEndDt(Date projEndDt) {
    this.projEndDt = projEndDt;
  }

  //@Column(name = "Program_Manager_Name")
  public String getProgramMangrNm() {
    return programMangrNm;
  }

  public void setProgramMangrNm(String programMangrNm) {
    this.programMangrNm = programMangrNm;
  }

  //@Column(name = "PM_Delegate_Name")
  public String getPmDelegateNm() {
    return pmDelegateNm;
  }

  public void setPmDelegateNm(String pmDelegateNm) {
    this.pmDelegateNm = pmDelegateNm;
  }

  ///@Column(name = "Project_Manager_Name")
  public String getProjMangerNm() {
    return projMangerNm;
  }

  public void setProjMangerNm(String projMangerNm) {
    this.projMangerNm = projMangerNm;
  }

  //@Column(name = "Active_Head_Count")
  public int getActiveHeadCount() {
    return activeHeadCount;
  }

  public void setActiveHeadCount(int activeHeadCount) {
    this.activeHeadCount = activeHeadCount;
  }

  //@Column(name = "Onsite_Active_Head_Count")
  public int getOnsActHeadCnt() {
    return onsActHeadCnt;
  }

  public void setOnsActHeadCnt(int onsActHeadCnt) {
    this.onsActHeadCnt = onsActHeadCnt;
  }

  //@Column(name = "Offshore_Active_Head_Count")
  public int getOffActHeadCnt() {
    return offActHeadCnt;
  }

  public void setOffActHeadCnt(int offActHeadCnt) {
    this.offActHeadCnt = offActHeadCnt;
  }

}
