package com.techm.pmo.model;
// Generated Jul 29, 2019 8:35:46 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.BatchSize;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TOsHrUser generated by hbm2java
 */
/*@Entity
@Table(name = "t_pmr", catalog = "pmox")*/
public class PrjmasterData implements java.io.Serializable {

	private String	businessUnit	;
	private String	projectId;
	private String	projectDescription	;
	private String status  ;
	private String projectStatus  ;
	private String  projectStartDate  ;
	private String  projectEndDate    ;
	private String closureDate    ;
	private String	project_location	;
	private String	sbu;
	private String ibg ;
	private String ibu ;
	private String ibuHeadId    ;
    private String  ibuHeadName   ;
    private String  pgmId  ;
    private String  pgmName    ;
    private String  pmId  ;
    private String  pmName    ;
    private String  projectMainType  ;
    private String  projectType    ;
    private String  deliveryOwnership;
    private String  projectCriticality ;
    private String  pricingModel   ;
    private String  projectTechnology;
    private String  projectDomain  ;
    private String  projectApplicationType    ;
    private String  digitalFlag    ;
    private String  digitalCategory    ;
    private String revTotal;
    private String ebidtaTotal;
    
    
    public String getBusinessUnit() {
      return businessUnit;
    }
    public void setBusinessUnit(String businessUnit) {
      this.businessUnit = businessUnit;
    }
    public String getProjectId() {
      return projectId;
    }
    public void setProjectId(String projectId) {
      this.projectId = projectId;
    }
    public String getProjectDescription() {
      return projectDescription;
    }
    public void setProjectDescription(String projectDescription) {
      this.projectDescription = projectDescription;
    }
    public String getStatus() {
      return status;
    }
    public void setStatus(String status) {
      this.status = status;
    }
    public String getProjectStatus() {
      return projectStatus;
    }
    public void setProjectStatus(String projectStatus) {
      this.projectStatus = projectStatus;
    }
    public String getProjectStartDate() {
      return projectStartDate;
    }
    public void setProjectStartDate(String projectStartDate) {
      this.projectStartDate = projectStartDate;
    }
    public String getProjectEndDate() {
      return projectEndDate;
    }
    public void setProjectEndDate(String projectEndDate) {
      this.projectEndDate = projectEndDate;
    }
    public String getClosureDate() {
      return closureDate;
    }
    public void setClosureDate(String closureDate) {
      this.closureDate = closureDate;
    }
    public String getProject_location() {
      return project_location;
    }
    public void setProject_location(String project_location) {
      this.project_location = project_location;
    }
    public String getSbu() {
      return sbu;
    }
    public void setSbu(String sbu) {
      this.sbu = sbu;
    }
    public String getIbg() {
      return ibg;
    }
    public void setIbg(String ibg) {
      this.ibg = ibg;
    }
    public String getIbu() {
      return ibu;
    }
    public void setIbu(String ibu) {
      this.ibu = ibu;
    }
    public String getIbuHeadId() {
      return ibuHeadId;
    }
    public void setIbuHeadId(String ibuHeadId) {
      this.ibuHeadId = ibuHeadId;
    }
    public String getIbuHeadName() {
      return ibuHeadName;
    }
    public void setIbuHeadName(String ibuHeadName) {
      this.ibuHeadName = ibuHeadName;
    }
    public String getPgmId() {
      return pgmId;
    }
    public void setPgmId(String pgmId) {
      this.pgmId = pgmId;
    }
    public String getPgmName() {
      return pgmName;
    }
    public void setPgmName(String pgmName) {
      this.pgmName = pgmName;
    }
    public String getPmId() {
      return pmId;
    }
    public void setPmId(String pmId) {
      this.pmId = pmId;
    }
    public String getPmName() {
      return pmName;
    }
    public void setPmName(String pmName) {
      this.pmName = pmName;
    }
    public String getProjectMainType() {
      return projectMainType;
    }
    public void setProjectMainType(String projectMainType) {
      this.projectMainType = projectMainType;
    }
    public String getProjectType() {
      return projectType;
    }
    public void setProjectType(String projectType) {
      this.projectType = projectType;
    }
    public String getDeliveryOwnership() {
      return deliveryOwnership;
    }
    public void setDeliveryOwnership(String deliveryOwnership) {
      this.deliveryOwnership = deliveryOwnership;
    }
    public String getProjectCriticality() {
      return projectCriticality;
    }
    public void setProjectCriticality(String projectCriticality) {
      this.projectCriticality = projectCriticality;
    }
    public String getPricingModel() {
      return pricingModel;
    }
    public void setPricingModel(String pricingModel) {
      this.pricingModel = pricingModel;
    }
    public String getProjectTechnology() {
      return projectTechnology;
    }
    public void setProjectTechnology(String projectTechnology) {
      this.projectTechnology = projectTechnology;
    }
    public String getProjectDomain() {
      return projectDomain;
    }
    public void setProjectDomain(String projectDomain) {
      this.projectDomain = projectDomain;
    }
    public String getProjectApplicationType() {
      return projectApplicationType;
    }
    public void setProjectApplicationType(String projectApplicationType) {
      this.projectApplicationType = projectApplicationType;
    }
    public String getDigitalFlag() {
      return digitalFlag;
    }
    public void setDigitalFlag(String digitalFlag) {
      this.digitalFlag = digitalFlag;
    }
    public String getDigitalCategory() {
      return digitalCategory;
    }
    public void setDigitalCategory(String digitalCategory) {
      this.digitalCategory = digitalCategory;
    }
    public String getRevTotal() {
      return revTotal;
    }
    public void setRevTotal(String revTotal) {
      this.revTotal = revTotal;
    }
    public String getEbidtaTotal() {
      return ebidtaTotal;
    }
    public void setEbidtaTotal(String ebidtaTotal) {
      this.ebidtaTotal = ebidtaTotal;
    }
    	

}
